// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loepdymvrijobjnmrmca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvZXBkeW12cmlqb2Jqbm1ybWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MTIyMTEsImV4cCI6MjA3Mzk4ODIxMX0.XDfnXoNZLMGBMBwqA-rbo5EvXR4vSg52Tv2hRN9AIUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});